services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - /api/.env
    networks:
      - tales
  
  yii:
    build: ./yii2
    container_name: yii2
    hostname: localhost
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - ./yii2:/var/www/html
      - ./apache/conf:/etc/apache2/sites-enabled/
    networks:
      - tales

networks:
  tales:
    driver: bridge